package com.company.Visitor;
import com.company.ASTnodes.*;

public interface ASTVisitorInterface<T> {
    T Visit(AdditionNode node);
    T Visit(AndNode node);
    T Visit(AssignmentNode node);
    T Visit(CaseNode node);
    T Visit(ControlNode node);
    T Visit(DeclareMatrixNode node);
    T Visit(DivisionNode node);
    T Visit(DotProductNode node);
    T Visit(ElseIfNode node);
    T Visit(ElseNode node);
    T Visit(EqualNode node);
    T Visit(ExpressionNode node);
    T Visit(ForNode node);
    T Visit(FunctioDefinitionNode node);
    T Visit(FunctionCallNode node);
    T Visit(GreaterOrEqualNode node);
    T Visit(GreaterThanNode node);
    T Visit(IfNode node);
    T Visit(InfixExpressionNode node);
    T Visit(IterationNode node);
    T Visit(LessOrEqualNode node);
    T Visit(LessThanNode node);
    T Visit(LogicalNode node);
    T Visit(MatrixAddtionNode node);
    T Visit(MatrixCrossProductNode node);
    T Visit(MatrixDeterminatNode node);
    T Visit(MatrixInverseNode node);
    T Visit(MatrixMultiplicationNode node);
    T Visit(MatrixRREFNode node);
    T Visit(MatrixSubtractionNode node);
    T Visit(MatrixTraceNode node);
    T Visit(MatrixTransposeNode node);
    T Visit(MinusNode node);
    T Visit(ModuloNode node);
    T Visit(MultiplicationNode node);
    T Visit(NotEqualNode node);
    T Visit(NotNode node);
    T Visit(OrNode node);
    T Visit(ParametersNode node);
    T Visit(ParenthesisExpressionNode node);
    T Visit(ParenthesisLogicalNode node);
    T Visit(PlusNode node);
    T Visit(ReturnNode node);
    T Visit(ScalarMultiplicationNode node);
    T Visit(SimpleExpressionNode node);
    T Visit(SubtractionNode node);
    T Visit(SwitchNode node);
    T Visit(VariableDeclarationNode node);
    T Visit(WhileNode node);

}
